# Generated by Django 4.1.3 on 2022-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobno',
            field=models.CharField(max_length=20),
        ),
    ]
