# Generated by Django 4.1.3 on 2022-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_student_dob_alter_student_mobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='mobno',
            field=models.CharField(max_length=10),
        ),
    ]
