# Generated by Django 4.1.3 on 2022-12-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('rollno', models.IntegerField()),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=20)),
                ('mobno', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=500)),
                ('section', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior')], max_length=2)),
            ],
        ),
    ]
