# Generated by Django 4.1.3 on 2022-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_student_secondary_rename_student_student_primary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_secondary',
            new_name='student',
        ),
        migrations.DeleteModel(
            name='student_primary',
        ),
    ]
