# Generated by Django 4.1.3 on 2022-12-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_rename_student_secondary_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=20)),
                ('mobno', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=500)),
            ],
        ),
    ]
