# Generated by Django 4.1.3 on 2022-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='add',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
